services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  
      - "5672:5672"    
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  scheduler:
    build: ./scheduler
    depends_on:
      - rabbitmq

volumes:
  mongo-data:
